require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TestCategoriesController do

  # This should return the minimal set of attributes required to create a valid
  # TestCategory. As you add validations to TestCategory, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all test_categories as @test_categories" do
      test_category = TestCategory.create! valid_attributes
      get :index
      assigns(:test_categories).should eq([test_category])
    end
  end

  describe "GET show" do
    it "assigns the requested test_category as @test_category" do
      test_category = TestCategory.create! valid_attributes
      get :show, :id => test_category.id.to_s
      assigns(:test_category).should eq(test_category)
    end
  end

  describe "GET new" do
    it "assigns a new test_category as @test_category" do
      get :new
      assigns(:test_category).should be_a_new(TestCategory)
    end
  end

  describe "GET edit" do
    it "assigns the requested test_category as @test_category" do
      test_category = TestCategory.create! valid_attributes
      get :edit, :id => test_category.id.to_s
      assigns(:test_category).should eq(test_category)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TestCategory" do
        expect {
          post :create, :test_category => valid_attributes
        }.to change(TestCategory, :count).by(1)
      end

      it "assigns a newly created test_category as @test_category" do
        post :create, :test_category => valid_attributes
        assigns(:test_category).should be_a(TestCategory)
        assigns(:test_category).should be_persisted
      end

      it "redirects to the created test_category" do
        post :create, :test_category => valid_attributes
        response.should redirect_to(TestCategory.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved test_category as @test_category" do
        # Trigger the behavior that occurs when invalid params are submitted
        TestCategory.any_instance.stub(:save).and_return(false)
        post :create, :test_category => {}
        assigns(:test_category).should be_a_new(TestCategory)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TestCategory.any_instance.stub(:save).and_return(false)
        post :create, :test_category => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested test_category" do
        test_category = TestCategory.create! valid_attributes
        # Assuming there are no other test_categories in the database, this
        # specifies that the TestCategory created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TestCategory.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => test_category.id, :test_category => {'these' => 'params'}
      end

      it "assigns the requested test_category as @test_category" do
        test_category = TestCategory.create! valid_attributes
        put :update, :id => test_category.id, :test_category => valid_attributes
        assigns(:test_category).should eq(test_category)
      end

      it "redirects to the test_category" do
        test_category = TestCategory.create! valid_attributes
        put :update, :id => test_category.id, :test_category => valid_attributes
        response.should redirect_to(test_category)
      end
    end

    describe "with invalid params" do
      it "assigns the test_category as @test_category" do
        test_category = TestCategory.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TestCategory.any_instance.stub(:save).and_return(false)
        put :update, :id => test_category.id.to_s, :test_category => {}
        assigns(:test_category).should eq(test_category)
      end

      it "re-renders the 'edit' template" do
        test_category = TestCategory.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TestCategory.any_instance.stub(:save).and_return(false)
        put :update, :id => test_category.id.to_s, :test_category => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested test_category" do
      test_category = TestCategory.create! valid_attributes
      expect {
        delete :destroy, :id => test_category.id.to_s
      }.to change(TestCategory, :count).by(-1)
    end

    it "redirects to the test_categories list" do
      test_category = TestCategory.create! valid_attributes
      delete :destroy, :id => test_category.id.to_s
      response.should redirect_to(test_categories_url)
    end
  end

end
